"""Build a standalone binary for mem-cli using PyInstaller.

Usage:
    python scripts/build_binary.py

Produces dist/mem/ (onedir) ready to be packaged as a tarball.
"""

from __future__ import annotations

import platform
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
_BAKED_VERSION_FILE = ROOT / "src" / "mem" / "_baked_version.py"


def asset_name() -> str:
    system = platform.system().lower()
    machine = platform.machine().lower()
    arch = "arm64" if machine in ("arm64", "aarch64") else "amd64"
    os_name = "darwin" if system == "darwin" else "linux"
    return f"mem-{os_name}-{arch}"


def _current_version() -> str:
    changelog = ROOT / "CHANGELOG.md"
    if changelog.exists():
        text = changelog.read_text(encoding="utf-8")
        m = re.search(r"^## \[(\d+\.\d+\.\d+)\]", text, re.MULTILINE)
        if m:
            return m.group(1)
    return "0.0.0"


def build() -> Path:
    version = _current_version()
    _BAKED_VERSION_FILE.write_text(
        f'# Auto-generated by build_binary.py — do not edit\nVERSION = "{version}"\n',
        encoding="utf-8",
    )
    try:
        sep = ";" if sys.platform == "win32" else ":"
        prompts_src = ROOT / "src" / "mem" / "prompts"
        add_data = f"{prompts_src}{sep}mem/prompts"

        subprocess.run(
            [
                sys.executable, "-m", "PyInstaller",
                "--onedir",
                "--name", "mem",
                "--add-data", add_data,
                "--copy-metadata", "mem-cli",
                "--hidden-import", "mcp",
                "--hidden-import", "typer",
                "--hidden-import", "rich",
                "--noconfirm",
                str(ROOT / "scripts" / "mem_entry.py"),
            ],
            cwd=ROOT,
            check=True,
        )
    finally:
        _BAKED_VERSION_FILE.unlink(missing_ok=True)
    return ROOT / "dist" / "mem"


if __name__ == "__main__":
    dist_dir = build()
    name = asset_name()
    print(f"asset={name}")
    print(f"dist={dist_dir}")
